name: 「推し」の最近のユーチューブ動画
on:
  schedule:
    - cron: "0 15 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: ${{ secrets.YOUTUBE_CHANNEL_ID }}
          lang: ja
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          max_videos: 12
          card_width: 187
          show_duration: true
          output_only: false
          output_type: html
