name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: { { secrets.YOUTUBE_CHANNEL_ID } }
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          comment_tag_name: YOUTUBE-CARDS
          show_duration: true
          max_videos: 6
          output_type: html
          lang: ja
          card_width: 278
